### PR TITLE
allow injection of custom object mapper

### PR DESCRIPTION
**Pull request by kobisuissa**

### CODE REVIEW

**Comment by kobisuissa** [comment]
@stritti could you please have a look at the PR checker job?  does it set the required AIRTABLE_API_KEY variable?  I merely added one test (and tested it locally), doesn't make sense that I broke all tests...  Thanks!

**Comment by Zelle97** [comment]
Hello kobisuissa thank you for your PR!

The Travis CI removed the environment variables for security reasons. 
Just found this in the doc: https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

I'm working on a fix for this, please be patient. Thanks!

**Comment by stritti** [comment]
@kobisuissa many thanks for your PR. @Zelle97 now has separated the integration tests from common unit tests. 
The integration tests are not run by travis on PRs now any more. Only the unit tests which are independent from the env variables.

**Comment by stritti** [comment]
@kobisuissa could you update your PR for the new structure, please?

**Comment by stritti** [comment]
Thank you very much @kobisuissa  for your enhancement.

**Comment by kobisuissa** [comment]
my pleasure @stritti do you have automatic deployment to bintray upon merge to master?

**Comment by stritti** [comment]
similar: I have to create a version tag :)

**Comment by stritti** [comment]
https://bintray.com/sybit-education/maven/airtable.java/0.1.3.n

**Pull request merged**
